apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: welcomeMessage
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: appKey
