apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
